import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css';
import 'react-bootstrap-icons'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ARCANA-TEAM-ONE',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-bs-theme="light">
      <body className={inter.className}>{children}</body>
    </html>
  )
}