ARG NODE_VERSION=21.7.3

################################################################################
# Use node image for base image for all stages.
FROM node:${NODE_VERSION}-alpine as base

WORKDIR /app

COPY ./package.json /app/

RUN npm install

COPY ./ /app/

EXPOSE 3000

CMD ["npm", "run", "dev"]