services:
  db:
    image: mongo:latest
    volumes:
      - arcana-db-data:/data/db
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    build:
      context: ./backend
      dockerfile: Dockerfile


  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
      args:
        FRONTEND_ENV: dev
    ports:
      - "5005:5005"
    volumes:
      - ./frontend:/app # Synchronise docker container with local change
      - /app/node_modules # Avoid re-copying local node_modules. Cache in volume. See https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
    env_file:
      - .env
    command: npm run dev -- --host

volumes:
  arcana-db-data: