services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend # Synchronise docker container with local change
    command: bash -c "python main.py"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend # Synchronise docker container with local change
    environment:
      - FRONTEND_ENV_URL=http://backend:8000

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - arcana-db-data:/data/db

volumes:
  arcana-db-data:
