# Use Kali Linux base image
FROM kalilinux/kali-rolling:latest

# Set environment variables for non-interactive apt installs
ENV DEBIAN_FRONTEND=noninteractive

# Update and install dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y [your-dependencies-here] && \
    apt-get clean

# Add your application files to the container
COPY ./CS4311_ARCANA_CUIBONO_Spring2024  /usr/src/CS4311_ARCANA_CUIBONO_Spring2024

# Set the working directory
WORKDIR /usr/src/CS4311_ARCANA_CUIBONO_Spring2024

# Install any required packages or perform setup tasks for your application
RUN [your-installation-or-setup-commands]
# RUN pip3 install -r requirements.txt
# RUN npm install --save


# Expose the ports your application uses
EXPOSE [your-port-here]
# EXPOSE 3000 or 4200 or 8080

# Define the command to run your application
CMD ["arcana"]
# CMD ["npm", "start"]
# CMD ["python3", "backend.py"]
# CMD ["uvicorn main:app --reload"]