services:

  backend:
    image: '${DOCKER_PACKAGE_REPOSITORY?Variable not set}/${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
    volumes:
      - arcana-static-data:/app/static
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  db:
    image: mongo:latest
    volumes:
      - arcana-db-data:/data/db
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"


  frontend:
    image: '${DOCKER_PACKAGE_REPOSITORY?Variable not set}/${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    build:
      context: ./frontend
      args:
        - FRONTEND_ENV=${FRONTEND_ENV-production}
    env_file:
      - .env

volumes:
  arcana-db-data:
  arcana-static-data: