# Use Kali Linux base image
FROM kalilinux/kali-rolling:latest

# Create directories for persistent data
RUN mkdir -p /data/db /data/app

# Define persistent volumes
VOLUME /data/db
VOLUME /data/app

# Set working directory
WORKDIR /app

COPY . .

EXPOSE 27017

