# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

# Want to help us make this template better? Share your feedback here: https://forms.gle/ybq9Krt8jtBL3iCk7

ARG PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION}-slim as base

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

WORKDIR /home/app/backend

COPY . /home/app/backend

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENV FAST_API_APP=main.py
ENV FAST_API_RUN_HOST=0.0.0.0
ENV FAST_API_RUN_PORT=5000

# Run the application.
CMD uvicorn 'main:app' --host ${FAST_API_RUN_HOST} --port ${FAST_API_RUN_PORT} --reload
